language: objective-c
osx_image: xcode10
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - PROJECT=SwiftLinkPreview.xcodeproj
script:
  - xcodebuild -project SwiftLinkPreview.xcodeproj -scheme SwiftLinkPreview         -destination "OS=12.0,name=iPhone 7"                      -sdk "iphonesimulator12.0"    RUN_TESTS="YES" BUILD_EXAMPLE="NO" POD_LINT="NO" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty -c;
  - xcodebuild -project SwiftLinkPreview.xcodeproj -scheme SwiftLinkPreviewWatchOS  -destination "OS=5.0,name=Apple Watch Series 4 - 44mm"    -sdk "watchsimulator5.0"      RUN_TESTS="NO"  BUILD_EXAMPLE="NO" POD_LINT="NO" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
  - xcodebuild -project SwiftLinkPreview.xcodeproj -scheme SwiftLinkPreviewTvOS     -destination "OS=12.0,name=Apple TV 1080p"                -sdk "appletvsimulator12.0"   RUN_TESTS="YES" BUILD_EXAMPLE="NO" POD_LINT="NO" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty -c;
  - xcodebuild -project SwiftLinkPreview.xcodeproj -scheme SwiftLinkPreviewMacOS    -destination "arch=x86_64"                                -sdk "macosx10.14"            RUN_TESTS="YES" BUILD_EXAMPLE="NO" POD_LINT="NO" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty -c;
  - bundle exec danger;
